Repository DeveloperAcademy-POSTECH/MC3-Team12-HangulKing, pull requests merged in 2022-07, with the labels that each got.

#16 Feat: LastVowelView
  HangulTop.xcodeproj/project.pbxproj
  HangulTop/AppDelegate.swift
  HangulTop/Assets.xcassets/vowel.imageset/Contents.json
  HangulTop/Assets.xcassets/vowel.imageset/vowel.png
  HangulTop/Screen/FirstVowel.storyboard
  HangulTop/Screen/LastVowel.storyboard
  HangulTop/Screen/StudyMenu.storyboard
  HangulTop/Screen/Vowel.storyboard
  HangulTop/ViewController/LastVowelViewController.swift
  HangulTop/ViewController/VowelViewController.swift
Labels: 루이

#38 Feat/record and play
  HangulTop.xcodeproj/project.pbxproj
  HangulTop/Screen/Consonant.storyboard
  HangulTop/Sound.mp3
  HangulTop/ViewController/ConsonantViewController.swift
Labels: 코인

#39 :bug: Fix soundbug
  HangulTop/ViewController/ConsonantViewController.swift
Labels: 코인

#41 Feat/vowel consonant batchim refactoring
  HangulTop.xcodeproj/project.pbxproj
  HangulTop/AppDelegate.swift
  HangulTop/Screen/Consonant.storyboard
  HangulTop/Screen/StudyMenu.storyboard
  HangulTop/ViewController/ConsonantEndViewController.swift
  HangulTop/ViewController/ConsonantViewController.swift
  HangulTop/ViewController/StudyMenuViewController.swift
  HangulTop/ViewController/SyllableStartViewController.swift
Labels: 코인

#44 Refactor invention principle
  HangulTop.xcodeproj/project.pbxproj
  HangulTop/Screen/Principle.storyboard
  HangulTop/ViewController/PrincipleCollectionViewCell.swift
  HangulTop/ViewController/PrincipleModel.swift
  HangulTop/ViewController/PrincipleViewController.swift
Labels: 소피

#49 Feat/bug fix
  HangulTop/Screen/Principle.storyboard
  HangulTop/Screen/Quiz.storyboard
  HangulTop/Screen/StudyMenu.storyboard
  HangulTop/ViewController/ConsonantViewController.swift
  HangulTop/ViewController/PrincipleCollectionViewCell.swift
  HangulTop/ViewController/PrincipleEndViewController.swift
  HangulTop/ViewController/QuizViewController.swift
  HangulTop/ViewController/StudyMenuViewController.swift
Labels: 코인

#53 Style: Custom Font Setting
  HangulTop.xcodeproj/project.pbxproj
  HangulTop/Font/EBS훈민정음L.otf
  HangulTop/Font/EBS훈민정음R.otf
  HangulTop/Font/EBS훈민정음SB.otf
  HangulTop/Info.plist
  HangulTop/Screen/Base.lproj/Main.storyboard
Labels: 루이

#55 Feat/add hangul view
  HangulTop.xcodeproj/project.pbxproj
  HangulTop/Screen/HangulView.storyboard
  HangulTop/Screen/StudyMenu.storyboard
  HangulTop/ViewController/HangulViewController.swift
Labels: 코인

#60 :bug: MainView BugFix
  HangulTop/ViewController/StudyMenuViewController.swift
Labels: 코인

#62 Style: QuizViewAutolayout (#61)
  HangulTop/Assets.xcassets/AccentColor.colorset/Contents.json
  HangulTop/Assets.xcassets/quiz.imageset/Contents.json
  HangulTop/Assets.xcassets/quiz.imageset/Group 84.pdf
  HangulTop/Screen/Quiz.storyboard
  HangulTop/ViewController/QuizViewController.swift
Labels: 루이

#66 Feat/edit hangul view
  HangulTop/Screen/HangulView.storyboard
  HangulTop/ViewController/HangulViewController.swift
Labels: 코인

#70 :iphone: Portrait Mod Fix
  HangulTop/AppDelegate.swift
Labels: 코인

#74 :heavy_plus_sign: Add Lottie-ios
  HangulTop.xcodeproj/project.pbxproj
  HangulTop/LottieManage/LottieManage.swift
  HangulTop/LottieManage/batchim.json
  HangulTop/LottieManage/finish.json
  HangulTop/LottieManage/quiz.json
  HangulTop/LottieManage/vowel.json
Labels: 코인
