Repository DeveloperAcademy-POSTECH/MC3-Team12-HangulKing, pull requests merged in 2022-08, with the labels that each got.

#81 Feat/edit hangul, Upgrade Record
  HangulTop/Screen/Consonant.storyboard
  HangulTop/Screen/HangulView.storyboard
  HangulTop/ViewController/ConsonantViewController.swift
Labels: 코인

#82 Style: LottieImage
  HangulTop/LottieManage/quiz.json
  HangulTop/Screen/Quiz.storyboard
  HangulTop/ViewController/QuizViewController.swift
Labels: 루이, 레티샤

#85 :green_heart: 출시 사전 준비 관련 프로젝트 파일 수정
  HangulTop.xcodeproj/project.pbxproj
  HangulTop/Screen/Consonant.storyboard
  HangulTop/Screen/StudyMenu.storyboard
  HangulTop/Screen/Vowel.storyboard
  HangulTop/ViewController/InformationModalViewController.swift
Labels: 코인

#87 Team Change
  HangulTop.xcodeproj/project.pbxproj
Labels: 루이

#92 :bento: Add Icon Asset
  HangulTop.xcodeproj/project.pbxproj
  HangulTop/Assets.xcassets/AppIcon.appiconset/1024.png
  HangulTop/Assets.xcassets/AppIcon.appiconset/120-1.png
  HangulTop/Assets.xcassets/AppIcon.appiconset/120.png
  HangulTop/Assets.xcassets/AppIcon.appiconset/180.png
  HangulTop/Assets.xcassets/AppIcon.appiconset/40.png
  HangulTop/Assets.xcassets/AppIcon.appiconset/58.png
  HangulTop/Assets.xcassets/AppIcon.appiconset/60.png
  HangulTop/Assets.xcassets/AppIcon.appiconset/80.png
  HangulTop/Assets.xcassets/AppIcon.appiconset/87.png
  HangulTop/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: 레티샤, 코인

#97 Feat/add app icon
  HangulTop.xcodeproj/project.pbxproj
  HangulTop/Assets.xcassets/AppIcon.appiconset/1024.png
  HangulTop/Assets.xcassets/AppIcon.appiconset/120-1.png
  HangulTop/Assets.xcassets/AppIcon.appiconset/120.png
  HangulTop/Assets.xcassets/AppIcon.appiconset/180.png
  HangulTop/Assets.xcassets/AppIcon.appiconset/40.png
  HangulTop/Assets.xcassets/AppIcon.appiconset/58.png
  HangulTop/Assets.xcassets/AppIcon.appiconset/60.png
  HangulTop/Assets.xcassets/AppIcon.appiconset/80.png
  HangulTop/Assets.xcassets/AppIcon.appiconset/87.png
  HangulTop/Assets.xcassets/AppIcon.appiconset/Contents.json
  HangulTop/ViewController/QuizViewController.swift
Labels: 코인

#98 :zap: Update HangulView AutoLayOut
  HangulTop/Screen/HangulView.storyboard
Labels: 코인

#100 :bug: Sound Bug Fix
  HangulTop/ViewController/ConsonantViewController.swift
  HangulTop/ViewController/HangulViewController.swift
  HangulTop/ViewController/QuizViewController.swift
Labels: 코인
